trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '*'  # This means any file in the repository.
    exclude:
      - '*.*'  # This excludes all files with a file extension, so only directories will match.
      - '**/*.md'  # This ensures the pipeline doesn't run for markdown changes.

pr: none  # This prevents the build from running when a pull request is opened.

pool:
  vmImage: 'windows-latest'  # Changed from 'ubuntu-latest' to 'windows-latest'

jobs:
  - job: InstallAndTest
    strategy:
      matrix:
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        addToPath: true
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    # Running test_play_sound.py
    - script: python -m unittest test_play_sound.py
      displayName: 'Run test_play_sound.py'

    # Running test_create_connection.py
    - script: python -m unittest test_create_connection.py
      displayName: 'Run test_create_connection.py'

    # Running test_find_item.py
    - script: python -m unittest test_find_item.py
      displayName: 'Run test_find_item.py'
